######################################################################
# Automatically generated by qmake (3.0) Sat Mar 14 12:25:55 2015
######################################################################

CONFIG += c++11 -Wall -Wextra -pedantic
QT += core gui widgets
TEMPLATE = app
TARGET = mcellGUI
INCLUDEPATH += .

# Input
HEADERS += mainWindow.hpp molModel.hpp molWidget.hpp
FORMS += ui/mainWindow.ui ui/molWidget.ui
SOURCES += mainWindow.cpp mcellGUI.cpp molModel.cpp molWidget.cpp
